// Generated by CoffeeScript 1.4.0
(function() {
  var Airport, EventEmitter, exec, plist, spawn, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

  EventEmitter = require('events').EventEmitter;

  plist = require('plist');

  Airport = (function(_super) {

    __extends(Airport, _super);

    function Airport(options) {
      var _base, _base1, _base2, _ref1, _ref2, _ref3;
      this.options = options != null ? options : {};
      this.logger = __bind(this.logger, this);

      this.sniff = __bind(this.sniff, this);

      this.prefs = __bind(this.prefs, this);

      this.help = __bind(this.help, this);

      this.disassociate = __bind(this.disassociate, this);

      this.getinfo = __bind(this.getinfo, this);

      this.scan = __bind(this.scan, this);

      this._execAndParse = __bind(this._execAndParse, this);

      this._parse = __bind(this._parse, this);

      this._exec = __bind(this._exec, this);

      this._system = __bind(this._system, this);

      if ('string' === typeof this.options) {
        this.options = {
          iface: this.options
        };
      }
      if ((_ref1 = (_base = this.options).airport_bin) == null) {
        _base.airport_bin = '/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport';
      }
      if ((_ref2 = (_base1 = this.options).iface) == null) {
        _base1.iface = 'en0';
      }
      if ((_ref3 = (_base2 = this.options).verbose) == null) {
        _base2.verbose = false;
      }
    }

    Airport.prototype._system = function(args) {
      return spawn(this.options.airport_bin, args, {
        stdio: "inherit"
      });
    };

    Airport.prototype._exec = function(args, fn) {
      var command;
      if ('string' === typeof args) {
        args = [args];
      }
      command = "" + this.options.airport_bin + " " + (args.join(' '));
      if (this.options.verbose) {
        console.info(command);
      }
      return exec(command, fn);
    };

    Airport.prototype._parse = function(buffer, fn) {
      try {
        return fn(false, plist.parseStringSync(buffer));
      } catch (e) {
        return fn(true, e);
      }
    };

    Airport.prototype._execAndParse = function(args, fn) {
      var _this = this;
      return this._exec(args, function(err, stdout, stderr) {
        if (err) {
          return fn(err, {
            stdout: stdout,
            stderr: stderr
          });
        }
        return _this._parse(stdout, fn);
      });
    };

    Airport.prototype.scan = function(arg, fn) {
      if (arg == null) {
        arg = '';
      }
      if (fn == null) {
        fn = null;
      }
      if ('function' === typeof arg) {
        fn = arg;
        arg = '';
      }
      return this._execAndParse(["--scan" + arg, "--xml"], fn);
    };

    Airport.prototype.getinfo = function(fn) {
      return this._execAndParse(["--getinfo", "--xml"], fn);
    };

    Airport.prototype.disassociate = function(fn) {
      return this._exec('--disassociate');
    };

    Airport.prototype.help = function(fn) {
      return this._exec('--help', fn);
    };

    Airport.prototype.prefs = function(name, value, fn) {
      var args, _ref1, _ref2;
      if (value == null) {
        value = null;
      }
      if (fn == null) {
        fn = null;
      }
      if ('function' === typeof name) {
        _ref1 = [null, null, name], name = _ref1[0], value = _ref1[1], fn = _ref1[2];
      } else if ('function' === typeof value) {
        _ref2 = [name, null, value], name = _ref2[0], value = _ref2[1], fn = _ref2[2];
      }
      args = [this.options.iface, 'prefs'];
      if (value) {
        args.push("" + name + "=" + value);
      } else if (name) {
        args.push("" + name);
      }
      return this._exec(args, fn);
    };

    Airport.prototype.sniff = function(channel) {
      var args;
      if (channel == null) {
        channel = null;
      }
      args = [this.options.iface, 'sniff'];
      if (channel) {
        args.push(channel);
      }
      return this._system(args);
    };

    Airport.prototype.logger = function() {
      return this._system([this.options.iface, 'logger']);
    };

    return Airport;

  })(EventEmitter);

  module.exports = {
    Airport: Airport
  };

}).call(this);
