// Generated by CoffeeScript 1.4.0
(function() {
  var Airport, airport;

  Airport = require('..').Airport;

  airport = new Airport;

  airport.getinfo(function(err, info) {
    return console.log(err, info);
  });

}).call(this);
