// Generated by CoffeeScript 1.4.0
(function() {
  var Airport, airport;

  Airport = require('..').Airport;

  airport = new Airport;

  airport.help(function(err, help) {
    return console.log(help);
  });

}).call(this);
