// Generated by CoffeeScript 1.4.0
(function() {
  var Airport, airport;

  Airport = require('..').Airport;

  airport = new Airport;

  airport.prefs('DisconnectOnLogout', function(err, value) {
    return console.log(err, value);
  });

  airport.prefs('DisconnectOnLogout', 'NO', function(err, value) {
    return console.log(err, value);
  });

}).call(this);
